### ISSUE TITLE
Change in index

### ISSUE THREAD

**Issue by frappaaa** [frappaaa/frappaaa#4]
Aggiungere alla lista di social link l'icona per ogni social e cambiare lo stile in 
```css
aside li{
background-color: grey;
border-radius: $radius/2;
list-style-type:none;
}
````
